# .pages.yml — leme media PagesCMS config for luigisimiani.com
# Docs: https://pagescms.org/docs/configuration
# Managed by: leme media

media:
  - name: images
    label: Images
    input: public/images
    output: /images
    categories: [ image ]

content:
  # ─── HOME ───────────────────────────────────────

  - name: hero-slideshow
    label: "Home: Hero Slideshow"
    type: file
    path: content/hero.json
    format: json
    description: "Full-screen hero slides with separate desktop/mobile images"
    fields:
      - name: slides
        label: Slides
        type: object
        list: true
        fields:
          - name: galleryId
            label: Link to Gallery
            type: string
            description: "Gallery slug (e.g. vogue-2024)"
          - name: desktopImage
            label: Desktop Image (vertical)
            type: image
            description: "Portrait/vertical for desktop screens"
          - name: mobileImage
            label: Mobile Image (horizontal)
            type: image
            description: "Landscape/horizontal for mobile screens"

  - name: quotes
    label: "Home: Quotes"
    type: file
    path: content/quotes.json
    format: json
    description: "Displayed between featured galleries on the homepage"
    fields:
      - name: quotes
        label: Quotes
        type: object
        list: true
        fields:
          - name: text
            label: Quote
            type: text
          - name: author
            label: Author
            type: string

  # ─── ABOUT ──────────────────────────────────────

  - name: bio
    label: "About: Bio"
    type: file
    path: content/bio.json
    format: json
    fields:
      - name: paragraphs
        label: Paragraphs
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
            hidden: true
          - name: value
            label: Text
            type: text

  - name: film-strip
    label: "About: Film Strip"
    type: file
    path: content/film-strip.json
    format: json
    description: "Scrolling film strip on the About page"
    fields:
      - name: images
        label: Images
        type: image
        list: true

  # ─── CONTACT ────────────────────────────────────

  - name: contact
    label: "Contact"
    type: file
    path: content/contact.json
    format: json
    fields:
      - name: email
        label: Email
        type: string
      - name: location
        label: Location
        type: string
      - name: instagram
        label: Instagram
        type: string
      - name: linkedin
        label: LinkedIn
        type: string

  # ─── GALLERY ────────────────────────────────────

  - name: galleries
    label: "Gallery"
    type: collection
    path: content/gallery
    format: json
    filename: "{primary}.json"
    fields:
      - name: id
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: subTitle
        label: Subtitle
        type: string
      - name: date
        label: Date
        type: date
      - name: password
        label: Password
        type: string
        description: "Leave empty for public galleries"
      - name: coverPhoto
        label: Cover Photo
        type: image
      - name: imageUrls
        label: Photos
        type: image
        list: true
      - name: imageAspectRatios
        label: Aspect Ratios
        type: number
        list: true
        hidden: true
    view:
      fields: [ title, date ]
      sort: [ date, title ]
      default:
        sort: date
        order: desc

settings:
  content:
    merge: true
