# .pages.yml — leme media PagesCMS config for luigisimiani.com
# Docs: https://pagescms.org/docs/configuration
# Managed by: leme media

media:
  - name: images
    label: Images
    input: public/images
    output: /images
    categories: [ image ]

content:
  - name: home
    label: Home
    type: file
    path: content/home.json
    format: json
    fields:
      - name: slides
        label: Hero Slideshow
        type: object
        list: true
        fields:
          - name: galleryId
            label: Link to Gallery
            type: string
            description: "Gallery slug (e.g. vogue-2024)"
          - name: desktopImage
            label: Desktop Image (vertical)
            type: image
          - name: mobileImage
            label: Mobile Image (horizontal)
            type: image
      - name: quotes
        label: Quotes
        type: object
        list: true
        fields:
          - name: text
            label: Quote
            type: text
          - name: author
            label: Author
            type: string

  - name: about
    label: About
    type: file
    path: content/about.json
    format: json
    fields:
      - name: paragraphs
        label: Bio
        type: object
        list: true
        fields:
          - name: id
            label: ID
            type: string
            hidden: true
          - name: value
            label: Text
            type: text
      - name: filmStrip
        label: Film Strip
        type: image
        list: true

  - name: contact
    label: Contact
    type: file
    path: content/contact.json
    format: json
    fields:
      - name: email
        label: Email
        type: string
      - name: location
        label: Location
        type: string
      - name: instagram
        label: Instagram
        type: string
      - name: linkedin
        label: LinkedIn
        type: string

  - name: galleries
    label: Gallery
    type: collection
    path: content/gallery
    format: json
    filename: "{primary}.json"
    fields:
      - name: id
        label: Slug
        type: string
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: subTitle
        label: Subtitle
        type: string
      - name: visibility
        label: Visibility
        type: select
        options:
          - { value: public, label: Public }
          - { value: password, label: Password Protected }
          - { value: hidden, label: Hidden }
        default: public
      - name: password
        label: Password
        type: string
        description: "Only used when visibility is 'Password Protected'"
      - name: tags
        label: Tags
        type: string
        list: true
        description: "e.g. featured, homepage, editorial, portrait"
      - name: date
        label: Date
        type: date
      - name: coverPhoto
        label: Cover Photo
        type: image
      - name: imageUrls
        label: Photos
        type: image
        list: true
      - name: imageAspectRatios
        label: Aspect Ratios
        type: number
        list: true
        hidden: true
    view:
      fields: [ title, visibility, tags, date ]
      sort: [ date, title ]
      default:
        sort: date
        order: desc

settings:
  content:
    merge: true
